language: java
jdk:
  - openjdk8
install: true
script: |
  docker run -d -p 3306:3306 --name=mysql -e MYSQL_ROOT_PASSWORD=123456 mysql
  docker run -d -p 6379:6379 --name=redis redis
  sleep 20
  docker exec -it mysql mysql -uroot -p123456 -e 'create database if not exists mall'
  mvn verify